---
- name: Role for configuring Nexus 9000 leaf switches
  hosts:  evpn_leaf
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      transport: cli
    nxapi:
      host: "{{ inventory_hostname }}"
      transport: nxapi
    day: "{{ hostvars[inventory_hostname]['ansible_date_time']['date'] }}"
    hr: "{{ hostvars[inventory_hostname]['ansible_date_time']['hour'] }}"
    min: "{{ hostvars[inventory_hostname]['ansible_date_time']['minute'] }}"
    sec: "{{ hostvars[inventory_hostname]['ansible_date_time']['second'] }}"

  roles:
    - {role: evpn_build_leaf, debug: on}

- name: Role for configuring BGP and uplinks on the spine switches
  hosts: evpn_spine
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      transport: cli
    nxapi:
      host: "{{ inventory_hostname }}"
      transport: nxapi
    day: "{{ hostvars[inventory_hostname]['ansible_date_time']['date'] }}"
    hr: "{{ hostvars[inventory_hostname]['ansible_date_time']['hour'] }}"
    min: "{{ hostvars[inventory_hostname]['ansible_date_time']['minute'] }}"
    sec: "{{ hostvars[inventory_hostname]['ansible_date_time']['second'] }}"

  roles:
    - {role: evpn_update_spine, debug: on}
