---
- name: Build the initial configuration on the Spine switches
  hosts:  evpn-spine
  
  roles:
    - {role: evpn_build_spine, debug: on}

- name: Build the leaf switches
  hosts: evpn-leaf
  
  roles:
    - {role: evpn_build_leaf, debug: on}

- name: Update the Spine BGP and uplink configuration
  hosts: evpn-spine

  roles:
   - {role: evpn_update_spine,debug: on}

- name: Configure access ports
  hosts: evpn-leaf

  roles:
  - {role: configure_access_ports, debug: on}

- name: Add tenants
  hosts: evpn-leaf

  roles:
  - {role: evpn_add_tenant, debug: on}

- name: Add vlans
  hosts: evpn-leaf

  roles:
  - {role: evpn_add_vlan, debug: on}
 


