---

# tasks file for evpn_delete_vlan

  - name: Decrypt the password file
    include_vars: ./playbooks/passwords.yml

  - name: Import facts from a XLS file for a new EVPN Tenant
    xls_to_facts:
      src: "evpn_config_template.xlsx"

#  - name: Optionally display the facts
#    debug: var=spreadsheet

  - name: Create the configuration for vlan deletion
    template:
      src: "./roles/{{role}}/templates/delete_vlan.j2"
      dest: "./roles/{{role}}/files/__{{switchname}}.cfg"

  - name: Configure the Nexus through the NX-API
    nxapi_install_config:
      config_file: "./roles/{{role}}/files/__{{switchname}}.cfg"
      host: "{{inventory_hostname}}"
      username: "{{username}}"
      password: "{{password}}"
      debug: "{{debug}}"
#      debug: "true"
