---
# tasks file for evpn_update_spine 
  - name: Decrypt the password file
    include_vars: ./playbooks/passwords.yml

      
  - name: Import facts from a XLS file for uplink ports
    xls_to_facts:
      src: "evpn_config_template.xlsx"

# Including the group_vars,  because they were being ignored (receiving Undefined Variable error)
  
  - name: Render spine uplink ports
    template:
      src: spine_uplinks.j2
      dest: "{{configuration_file[0].type}}"

  - name: Configure the spine switches through the NX-API
    nxapi_install_config:
      config_file: "{{item.type}}" 
      host: "{{inventory_hostname}}"
      username: "{{username}}"
      password: "{{password}}"
#      debug: "{{debug}}"
      debug: "true"
    with_items: "{{configuration_file}}"  
