---
# tasks file for evpn_update_spine 
     
  - name: Import facts from a XLS file for uplink ports
    xls_to_facts:
      src: "evpn_config_template.xlsx"

# Including the group_vars,  because they were being ignored (receiving Undefined Variable error)
  
  - name: Render spine uplink ports
    template:
      src: spine_uplinks.j2
      dest: "{{configuration_file[0].type}}"

  - name: Create a backup (checkpoint) of the current running configuration 
    nxos_rollback:
      checkpoint_file: ansible-"{{ day }}"-"{{ hr }}""{{ min }}""{{ sec }}".cfg
      provider: "{{ cli }}"

  - name: Send configuration to device
    nxos_config:
      provider: "{{ cli }}"
      src: "{{ item.type }}"
      defaults: yes
    register: result
    with_items: "{{ configuration_file }}"

  - name: Notify users of configuration change
    when: "{{ result['changed'] }}"
    nxos_command:
      provider: "{{ cli }}"
      commands: send * Configured by Ansible role {{role}} on {{ansible_date_time.date}} {{ansible_date_time.time}}

  - name: Display result
    debug: var=result['changed'] verbosity=0

#  - name: Configure the spine switches through the NX-API
#    nxapi_install_config:
#      config_file: "{{item.type}}" 
#      host: "{{inventory_hostname}}"
#      username: "{{username}}"
#      password: "{{password}}"
#      debug: "{{debug}}"
#      debug: "true"
#    with_items: "{{configuration_file}}"  
