---
# tasks file for evpn_build_spine 
  - name: Decrypt the password file
    include_vars: ./playbooks/passwords.yml
    no_log: True

  - name: Import host-specific facts from a XLS file
    xls_to_facts:
      src: "evpn_config_template.xlsx" 

#  - name: Optionally display the facts
#    debug: var=spreadsheet

  - name: Render switch global configuration commands 
    template:
      src: spine_global.j2
      dest: "{{configuration_file.type}}"

  - name: Configure the spine switches through the NX-API
    nxapi_install_config:
      config_file: "{{configuration_file.type}}" 
      host: "{{inventory_hostname}}"
      username: "{{username}}"
      password: "{{password}}"
      debug: "{{debug}}"
