---
# tasks file for evpn_build_leaf 
  - name: Decrypt the password file
    include_vars: ./playbooks/passwords.yml

  - name: Import host-specific facts from a XLS file
    xls_to_facts:
      src: "evpn_config_template.xlsx" 

#  - name: Optionally display the facts
#    debug: var=spreadsheet

  - name: Render leaf global configuration commands
    template:
      src: leaf_global.j2
      dest: "{{configuration_file[0].type}}"
  
  - name: Generate BGP configuration for spine
    template:
      src: spine_global.j2
      dest: "./roles/evpn_update_spine/files/__spine_global.cfg" 

  - name: Render leaf uplink ports
    template:
      src: leaf_uplinks.j2
      dest: "{{configuration_file[1].type}}"

  - name: Configure the leaf switches through the NX-API
    nxapi_install_config:
      config_file: "{{item.type}}" 
      host: "{{inventory_hostname}}"
      username: "{{username}}"
      password: "{{password}}"
      debug: "{{debug}}"
    with_items: "{{configuration_file}}"  
